yarnPath: .yarn/releases/yarn-2.4.1.cjs
enableGlobalCache: true
nodeLinker: node-modules
compressionLevel: 0

packageExtensions:
  xunit-viewer@5.2.0:
    peerDependencies:
      "@babel/core": "*"

  typeson-registry@1.0.0-alpha.35:
    peerDependencies:
      regenerator-runtime: "*"
      core-js-bundle: "*"

  realistic-structured-clone@2.0.2:
    peerDependencies:
      regenerator-runtime: "*"
      core-js-bundle: "*"

  reakit-warning@0.5.5:
    peerDependencies:
      react-dom: "*"

  reakit-warning@0.6.1:
    peerDependencies:
      react-dom: "*"

  react-with-styles@3.2.3:
    peerDependencies:
      react-dom: "*"

  react-live@1.12.0:
    peerDependencies:
      react: "*"

  react-dev-utils@10.2.1:
    peerDependencies:
      webpack: "*"
      typescript: "*"

  jest-enzyme@7.1.2:
    peerDependencies:
      react: "*"

  fake-indexeddb@3.1.0:
    peerDependencies:
      regenerator-runtime: "*"
      core-js-bundle: "*"

  "@emotion/native@10.0.27":
    peerDependencies:
      "@emotion/core": "*"
      "react": "*"

  "@storybook/core@6.1.10":
    peerDependencies:
      "typescript": "*"

  "@storybook/react@6.1.10":
    peerDependencies:
      "typescript": "*"

  "@types/wordpress__block-editor@2.2.9":
    peerDependencies:
      "react": "*"
      "react-dom": "*"

  "@types/wordpress__components@9.8.6":
    peerDependencies:
      "react": "*"

  "@wordpress/block-editor@5.3.3":
    peerDependencies:
      "@wp-g2/create-styles": "*"
      "react": "*"
      "react-dom": "*"
      "reakit-utils": "*"
      "react-native": "*"

  "@wordpress/block-library@2.29.3":
    peerDependencies:
      "@wp-g2/create-styles": "*"
      "react": "*"
      "react-dom": "*"
      "reakit-utils": "*"
      "react-native": "*"

  "@wordpress/components@12.0.8":
    peerDependencies:
      "react": "*"
      "react-dom": "*"
      "react-native": "*"
      "@wordpress/data": "*"

  "@wordpress/components@13.0.3":
    peerDependencies:
      "react": "*"
      "react-dom": "*"
      "react-native": "*"
      "@wordpress/data": "*"

  "@wordpress/compose@3.25.3":
    peerDependencies:
       "react": "*"

  "@wordpress/data@4.27.3":
    peerDependencies:
      "react": "*"

  "@wordpress/edit-post@3.27.3":
    peerDependencies:
      "@wp-g2/create-styles": "*"
      "react": "*"
      "react-dom": "*"
      "reakit-utils": "*"
      "react-native": "*"

  "@wordpress/edit-site@1.17.3":
    peerDependencies:
      "@wp-g2/create-styles": "*"
      "reakit-utils": "*"
      "react": "*"
      "react-dom": "*"
      "react-native": "*"

  "@wordpress/editor@9.26.3":
    peerDependencies:
      "@wp-g2/create-styles": "*"
      "react": "*"
      "react-dom": "*"
      "reakit-utils": "*"
      "react-native": "*"

  "@wordpress/format-library@1.27.3":
    peerDependencies:
      "@wp-g2/create-styles": "*"
      "reakit-utils": "*"
      "react": "*"
      "react-dom": "*"
      "react-native": "*"

  "@wordpress/interface@2.0.2":
    peerDependencies:
      "@wp-g2/create-styles": "*"
      "reakit-utils": "*"
      "react": "*"
      "react-dom": "*"
      "react-native": "*"

  "@wordpress/jest-preset-default@7.0.3":
    peerDependencies:
      "@babel/core": "*"
      "react": "*"
      "react-dom": "*"

  "@wordpress/nux@3.25.3":
    peerDependencies:
      "@wp-g2/create-styles": "*"
      "reakit-utils": "*"
      "react": "*"
      "react-native": "*"
      "react-dom": "*"

  "@wordpress/postcss-plugins-preset@3.0.0":
    peerDependencies:
      "postcss": "*"

  "@wordpress/reusable-blocks@1.2.3":
    peerDependencies:
      "@wp-g2/create-styles": "*"
      "react": "*"
      "react-dom": "*"
      "react-native": "*"
      "reakit-utils": "*"

  "@wordpress/scripts@15.0.1":
    peerDependencies:
      "@babel/core": "*"
      "react": "*"
      "react-dom": "*"

  "@wordpress/server-side-render@1.21.3":
    peerDependencies:
      "@wp-g2/create-styles": "*"
      "react": "*"
      "react-dom": "*"
      "react-native": "*"
      "reakit-utils": "*"

  "@wordpress/url@2.22.2":
    peerDependencies:
      "react-native": "*"

  "@wp-g2/context@0.0.160":
    peerDependencies:
      "@wordpress/data": "*"
      "@wordpress/is-shallow-equal": "*"

  "@wp-g2/styles@0.0.140":
    peerDependencies:
      "@wordpress/data": "*"
      "@wordpress/is-shallow-equal": "*"

  "@wp-g2/styles@0.0.160":
    peerDependencies:
      "@wordpress/data": "*"
      "@wordpress/is-shallow-equal": "*"


  "@types/wordpress__blocks@6.4.12":
    peerDependencies:
      "react": "*"

  "@types/wordpress__editor@9.4.6":
    peerDependencies:
      "react": "*"
      "react-dom": "*"
      "react-native": "*"

  "@types/wordpress__media-utils@0.2.4":
    peerDependencies:
      "react": "*"
      "react-dom": "*"
      "react-native": "*"

  "@types/wordpress__plugins@2.3.7":
    peerDependencies:
      "react": "*"

  "@wordpress/annotations@1.24.8":
    peerDependencies:
      "react": "*"

  "@wordpress/api-fetch@3.21.5":
    peerDependencies:
      "react-native": "*"

  "@wordpress/api-fetch@4.0.0":
    peerDependencies:
      "react-native": "*"

  "@wordpress/blocks@7.0.6":
    peerDependencies:
      "react": "*"

  "@wordpress/blocks@8.0.3":
    peerDependencies:
      "react": "*"

  "@wordpress/core-data@2.26.3":
    peerDependencies:
      "react": "*"
      "react-native": "*"

  "@wordpress/data-controls@1.21.3":
    peerDependencies:
      "react": "*"
      "react-native": "*"

  "@wordpress/interface@1.0.6":
    peerDependencies:
      "react": "*"
      "react-dom": "*"
      "react-native": "*"

  "@wordpress/keyboard-shortcuts@1.14.3":
    peerDependencies:
      "react": "*"

  "@wordpress/list-reusable-blocks@1.25.8":
    peerDependencies:
      "react": "*"
      "react-dom": "*"
      "react-native": "*"
      "@wordpress/data": "*"

  "@wordpress/notices@2.13.3":
    peerDependencies:
      "react": "*"

  "@wordpress/plugins@2.25.3":
    peerDependencies:
      "react": "*"

  "@wordpress/rich-text@3.25.3":
    peerDependencies:
      "react": "*"

  "@wordpress/viewport@2.26.3":
    peerDependencies:
      "react": "*"

  "@wordpress/media-utils@1.20.3":
    peerDependencies:
      "react-native": "*"

  "@wp-g2/components@0.0.140":
    peerDependencies:
      "@wordpress/data": "*"
      "@wordpress/is-shallow-equal": "*"

  "@wp-g2/components@0.0.160":
    peerDependencies:
      "@wordpress/data": "*"
      "@wordpress/is-shallow-equal": "*"

  "@wp-g2/context@0.0.140":
    peerDependencies:
      "@wordpress/data": "*"
      "@wordpress/is-shallow-equal": "*"

  "newspack-blocks@*":
      dependencies:
        swiper: "5.0.0"
